test: 
	cd write_qminput_nma; ./run_test.x
	cd simplex_perfect_fit_NMA; ./run_test.x
	cd ga_perfect_fit_NMA; ./run_test.x
	cd dihedral_least_squares_NMA; ./run_test.x
	
clean:
	cd write_qminput_nma; rm -f *.dif *.gjf prog_out.txt
	cd simplex_perfect_fit_NMA; rm -f *.dif *.dat prog_out.txt
	cd ga_perfect_fit_NMA; rm -f *.dif *.dat prog_out.txt
	cd dihedral_least_squares_NMA; rm -f *.dif *.dat prog_out.txt

