#!/bin/sh

AMBERHOME=`dirname $0`

if [ "$AMBERHOME" ]; then

   $AMBERHOME/teLeap \
              -I$AMBERHOME/../share/amber/dat/leap/prep \
              -I$AMBERHOME/../share/amber/dat/leap/lib \
              -I$AMBERHOME/../share/amber/dat/leap/parm \
              -I$AMBERHOME/../share/amber/dat/leap/cmd \
               $*

else

   echo "Error: you must set the AMBERHOME environment variable!"
   exit 1 

fi
