#!/bin/sh

if [ "$AMBERHOME" ]; then

   XENVIRONMENT=$AMBERHOME/dat/XaLeap_wcl
   export XENVIRONMENT
   $AMBERHOME/bin/xaLeap \
              -I$AMBERHOME/dat/leap/prep \
              -I$AMBERHOME/dat/leap/lib \
              -I$AMBERHOME/dat/leap/parm \
              -I$AMBERHOME/dat/leap/cmd \
               $*

else

   echo "Error: you must set the AMBERHOME environment variable!"
   exit 1 

fi
